name: Deploy Express App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H 217.154.2.82 >> ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          rsync -avz --delete ./ root@217.154.2.82:/root/dinogaia/back

      - name: Install dependencies on VPS
        run: |
          ssh root@217.154.2.82"
          cd /root/dinogaia/back && 
          npm install
          "

      - name: Restart PM2 service for Express
        run: |
          ssh user@your-vps-address "
          cd /root/dinogaia/back &&
          pm2 start npm --name nest-app -- run start:dev || pm2 restart nest-app
          "
